language: node_js
node_js:
  - "6.10.3"
# add code climate report token
addons:
  code_climate:
    repo_token:
      secure: "CO7h1+408grgwzqqbUFeKu1tgCuV3HqCyK86IMG1u0mA/0bZtNMl1WCxvniS8Cvb/EtONwD3wvfE2cP9EdmQDaVA7C2o0fay8hSp9Ht1tE53IucueS5WtQ5iVKTmZ+Ow9zCfXaeC309f/dk553iuSv1L6xYJvoTGu2EZ6pqIbyeFp7MoWRNkaUEAFDzB5LtSc69vkO9W3QjOG9qxb9c+6Eo8b+FV8Tpp6RynrPcITLCm0R9L3Q60R8CN92zsn5nv25n/iOWOlBmiHj3bOHijlCVv5qcfmHNponpetAMqu8WQf29rEncxok3KRSCGvl5Kx+bnTonmdr8bLZ7dqHazhdXGVqTvab4Qo9woA+/kauZVUO2poXU9gutLOAklBEnLLcCUEVeKlcbkMungusUgvCZ155+i/amK3Bvf5u5GbU4tiGCOiiEyjhNP+Lcg5PHso+qlpveRtODJqIFYBxTRUkKgJTyYxV8SUrFNwlZMmd1UfMprV1zINiw64TbZAthdupqYYbJ67CiTgMN1m98N0k8yz/JZTLUXPhywGRONODaSfVG2iluAYZ6l1b7O7O9PmU1n1r9XfKwBhezwAbhNb2E1isSRrfWtb8R0zCaL9ToGIy4+ZSYVRKMWy+DizPuOrTQ5cW+wP3H0nu5O6V5tf9dXDYgy336plbf5UQWrbsg="

# run test
script: "npm run test"

# send coverage report to ci
after_success:
  - "npm run send:coverage"
  - codeclimate-test-reporter < coverage/lcov.info