language: node_js
node_js:
  - "6.10.3"
# add code climate report token
addons:
  code_climate:
    repo_token: token
# run test
script: "npm run test:build"

# send coverage report to ci
after_success:
  - "npm run send:coverage"
  - codeclimate-test-reporter < coverage/lcov.info