language: node_js
node_js:
  - "10.16.3"
# add codeclimate report token
env:
  global:
    - CC_TEST_REPORTER_ID=c30efe4967139073721ba0e5ae6a97c511c3bc53ce11144c0c2030bae9655c75

services:
  - postgresql

before_script:
  -  psql -c 'create database datamodela;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# run test
script: "npm run coverage2"

# send coverage report to ci
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  